try{
    function add(a, b){
        return a + b
    }
} catch(e){
    throw e
}